var category = {
'스킨/토너':'Toners',
'로션':'Lotions',
'크림':'Essences/Serums/Face Oils',
'에센스/세럼/페이스오일':'Creams',
'아이/넥/립케어':'Eye/Neck/Lip Care',
'미스트':'Face Mists',
'팩/마스크팩':'Face & Sheet Masks',
'스페셜케어/뷰티기기':'Special Care/Beauty Equipments',
'기초케어세트':'Skin Care Sets',
'로션/크림/젤':'Lotions/Creams/Gels',
'파우더/스틱/스프레이':'Powders/Sticks/Sprays',
'쿠션/팩트/애프터선케어/태닝/세트':'Cousions/Pacts/After Sun Care/Tanners/Sets',
'클렌징로션/크림/오일/젤':'Cleansing Lotions/Creams/Oils/Gels',
'클렌징폼/티슈':'Cleansing Forms/Tissues',
'립/아이리무버':'Lip/Eye Removers',
'필링/스크럽/피부관리용품/클렌징기기':'Peelings/Scrubs/Cleansing Tools',
'스킨/토너':'Toners',
'로션/에멀젼/세럼/크림/에센스':'Lotions/Emulsions/Serums/Creams/Essences',
'아이/립/넥케어':'Eye/Lip/Neck Care',
'미스트/마스크/팩':'Mists/Face & Sheet Masks',
'쉐이빙/애프터쉐이브':'Shave Creams/Aftershaves',
'클렌징':'Cleansers',
'선케어/메이크업':'Sun Care/Makeup',
'바디/헤어케어':'Body/Hair Care',
'스페셜케어/기초케어세트':'Special Care/Skin Care Sets',
'기초케어':'Skin Care',
'헤어/바디케어':'Hair/Body Care',
'스페셜케어/기초케어세트':'Special Care/Sets',
'베이스/프라이머':'Bases/Primers',
'BB/CC크림':'BB/CC Creams',
'파운데이션':'Foundation',
'쿠션팩트/파우더/트윈케익/컴팩트':'Cushions/Powders/Compacts',
'컨실러':'Concealers',
'블러셔/하이라이터/쉐딩':'Blush/Hightlighter/Contour',
'아이섀도우':'Eyebrow',
'아이라이너':'Eyeshadow',
'아이브로우':'Eyeliner',
'마스카라':'Mascara',
'립스틱':'Lipsticks',
'립글로스/립틴트':'Lip Gloss/Lip tints',
'립펜슬/립크레용/립라이너':'Lip pensils/Lip crayons/Lip Liners',
'립케어':'Lip Care',
'매니큐어/네일컬러':'Maincure/Nail color',
'네일케어/리무버/세트':'Nail Care/Nail Polish Removers/Nail Sets',
'세트':'Makeup Sets',
'팔레트':'Palettes',
'화장솜/퍼프/스펀지/기름종이':'Facial Cottion/Sponges/Blotting',
'케이스/손거울':'Cases/Mirrors',
'브러쉬':'Makeup Brushes',
'뷰러/기타도구':'Eyelash Curlers/Tools',
'바디워시':'Body Wash',
'바디스크럽/바디솔트/입욕제':'Body Scrubs/Body Salts/Bath Preparation',
'바디로션/크림':'Body Lotion/Creams',
'바디오일/미스트':'Body Oils/Sprays',
'바디슬리밍':'Body Slimming Treatments',
'썬케어/데오드란트/제모용품':'Sun Care/Deodorant/Shaving Tools',
'핸드/풋케어':'Hand/Foot care',
'구강케어/바디케어세트':'Oral Care/Body Care Sets',
'샴푸/바스':'Shampoos',
'린스/트리트먼트':'Conditioners/Treatments',
'에센스/팩':'Essences/Packs',
'미스트/오일':'Hair Mists/Oils',
'헤어스타일링':'Hair Styling Products',
'헤어케어세트':'hair Care Sets',
'여성향수':'Women',
'남성향수':'Men',
'세트/기타':'Sets',
'토트/숄더/크로스백':'Totes/Shoulder Bags/Crossbody Bags',
'클러치백/파우치':'Clutches/Pouches',
'백팩':'Paper/Laptop Bags',
'서류/노트북가방':'Backpacks',
'여행용가방':'Carry-Ons',
'액세서리':'Accessories',
'기타':'Others',
'장지갑':'Long Wallets',
'중/반지갑':'Bifold Wallet',
'머니클립':'Money Clips',
'카드/명합/키/동전지갑':'Card Cases/Key Holders/Coin Purses',
'여행/여권지갑':'Travel Pouch',
'럭셔리':'Luxury Watches',
'패션/캐주얼':'Fashion/Casual Watches',
'스포츠':'Sports Watche',
'아동':'kids Watche',
'귀걸이':'Earrings',
'목걸이/펜던트':'Necklaces/Pendant',
'팔찌/발찌/참':'Bracelets/Anklets/Charms',
'반지':'Rings',
'브로치/부토니에/기타':'Brooches/Pins/Other',
'헤어액세서리':'Hair Accessories',
'기타액세서리':'Other Accessories',
'패션선글라스':'Designer Sunglasses',
'스포츠선글라스':'Sports Sunglasses',
'안경테/아동선글라스/기타':'Eyewear Frames/kids Sunglasses/Eyewear Accessories',
'상/하의/원피스':'Clothing',
'언더웨어':'Underwear',
'양말/스타킹/레깅스':'Socks/Stockings/Leggings',
'벨트':'Belts',
'넥타이':'Neckties',
'스카프/머플러':'Scarves',
'모자/장갑':'Hats/Gloves',
'만년필/볼펜/다이어리':'Fountain Pens/Ball-poing Pens/Schedulers',
'라이터/소품':'Lighters/Props',
'기타잡화':'Other Accessories',
'구두/샌들/슬리퍼':'Sandals/Slippers',
'캐주얼/스니커즈운동화':'Casual Shoes/Sneakers',
'아동/기타신발':'Kid Shoes/Others',
'유아동패션':'kids Fashion',
'스포츠/레저':'Sports/Leisure',
'DSLR/디지털/즉석카메라':'Digital SLRs/Digital Cameras/Instant Cameras',
'캠코더':'Camcoders',
'카메라용품/렌즈':'Lenses/Accessories',
'노트북':'Laptops',
'태블릿':'Tablets',
'스마트폰/스마트워치/밴드':'Smart Phone/Smart Watches/Smart Bands',
'스마트폰악세서리/용품':'Smart Phone Accessories/Attachments',
'전기면도기/면도기':'Electric Razors/Razors',
'전동칫솔/칫솔':'Eletric Toothbrushes/Toothbrushes',
'주방가전':'Kitchen Appliances',
'소형가전/미용/마사지기':'Small Appliances/Beauty/Massage Equipments',
'이어폰/헤드폰':'Earphones/Headphones',
'스피커/기타 음향기기':'Speakers/Audio Equipments',
'기타영상기기':'Video Equipments',
'홍삼/인삼':'Red Ginseng/Ginseng',
'비타민제/영양제':'Multivitamins/Nutrients',
'다이어트/미용보조식품':'Diet Formulas/Beauty Supplements',
'유아동건강식품/기타건강식품':'Kids Health Food/Other Health Foods',
'초콜릿/캔디/스낵':'Chocolate/Cnady/Snack',
'커피/차':'Coffee/Tea',
'김/고추장/기타':'Dried Seaweed/Chile Paste/Others',
'주방/생활용품':'Kitchen/Household Goods',
'인테리어/소품':'Interior/Props   ',
"스킨케어":"Skincare",
"메이크업":"Makeup",
"바디/헤어/향수":"Perfumes/Body/Hair",
"가방/지갑":"Bags/Wallets",
"시계/주얼리":"Watches/jewelry",
"패션/잡화":"Fashion/Accessories",
"디지털":"Electronics",
"식품/리빙":"Grocery/Living",
"기초케어":"BASIC CARE",
"선케어":"SUN CARE",
"클렌징":"CLEANSERS",
"남성용":"MEN'S SKIN CARE",
"아동용":"BABY SKIN CARE",
"페이스":"FACE",
"아이":"EYES",
"립":"LIPS",
"네일":"NAILS",
"세트/팔레트":"MAKEUP SETS/PALETTES",
"바디케어":"BODY CARE",
"헤어케어":"HAIR CARE",
"향수":"PERFUMES",
"백팩/비즈니스가방":"BACKPACKS/BUSINESS BAGS",
"여행용가방":"TRAVEL":"BAGS",
"액세서리 및 기타":"ACCESSORIES",
"지갑":"WALLETS",
"시계":"WATCHES",
"주얼리":"JEWELRY",
"액세서리":"ACCESSORIES",
"선글라스/안경":"SUNGLASSES/GLASSES",
"의류":"CLOTHING",
"패션잡화":"FASHION ACCESSORIES",
"신발":"SHOES",
"유아동/스포츠":"KID/SPORTS",
"노트북/태블릿":"LAPTOPS/TABLETS",
"스마트기기":"SMART DEVICES",
"면도기/칫솔":"RAZORS/TOOTHBRUSHES",
"생활/소형가전":"HOME&SMALL APPLIANCES",
"영상/음향가전":"VIDEO/AUDIO",
"건강식품":"HEALTH FOOD",
"일반식품":"FOOD",
"리빙용품":"LIVING"
}
